[project]
name = "halfedge"
version = "0.12.1"
description = "A typical half-edge data structure with some padding"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Shay Hill", email = "shay_public@hotmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "paragraphs>=1.0.1",
]

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.12.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]


[tool.commitizen]
kame = "cz_conventional_commits"
version = "0.12.1"
tag_format = "$version"
major-version-zero = true
version_files = ["pyproject.toml:^version"]


[tool.isort]
profile = "black"


[tool.pytest.ini_options]
addopts = "--doctest-modules"
pythonpath = "tests"
log_cli = true
testpaths = ["tests"]
norecursedirs = ["src", ".git", ".venv", "__pycache__", "*.egg"]


[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    "S101",
    "D",
    "F401",
] # Ignore assertions, docstrings, unused imports in test files

[tool.ruff.format]
docstring-code-line-length = 88

[tool.ruff.lint]

select = ["ALL"]

ignore = [
    "PLR",  # magic values
    "COM",  # trailing commas
    "ANN",  # forbid Any
    "S",    # warnings about pickle, random, etc.
    "N",    # names
    "B019", # memory leak warning for lru_cache
]


[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__.py"]

pythonVersion = "3.11"
pythonPlatform = "All"

typeCheckingMode = "strict"
reportCallInDefaultInitializer = true
reportImplicitStringConcatenation = true
# reportMissingSuperCall = true
reportPropertyTypeMismatch = true
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = true
reportUnusedCallResult = true

venvPath = "."
venv = "./.venv"
